### ISSUE TITLE
No matching distribution found for djfirebirdsql

### ISSUE THREAD

**Issue by xvlady** [nakagami/djfirebirdsql#1]
(v2) C:\aprg\py\WoG2>pip install firebirdsql djfirebirdsql django
Collecting firebirdsql
  Using cached https://files.pythonhosted.org/packages/a5/fc/fb5754b1a84c6ea25157d0ed71b54ba34fc43a121b95e48046c49097253d/firebirdsql-1.1.0.tar.gz
Collecting djfirebirdsql
  Could not find a version that satisfies the requirement djfirebirdsql (from versions: )
No matching distribution found for djfirebirdsql

(v2) C:\aprg\py\WoG2>

**Comment by toninhonunes** [comment]
Me too, the pip of djfirebirdsql does not exist.

**Comment by nakagami** [comment]
now upload djfirebirdsql to pypi

**Comment by nakagami** [comment]
Now upload djfirebirdsql to pypi.
