### ISSUE TITLE
Error with django

### ISSUE THREAD

**Issue by juanmoura** [nakagami/djfirebirdsql#3]
DATABASES = {
    'default': {
        'ENGINE': 'djfirebirdsql',
        'NAME': 'C:/Users/JuanCarlos/PycharmProjects/FB_TEST/FB_TESTE/FB_TESTE/employee.fdb',
        'HOST': 'localhost',
        'USER': 'sysdba',
        'PASSWORD': 'masterkey',
    }
}

~/ $ python manage.py inspectdb

Try using 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'

**Comment by nakagami** [comment]
Sorry, now release new version. And please use with Django 3.0a1
```
pip install django==3.0a1
```
